<?php
//print_r($albumForm);die;
//$form->setAttribute('action', $this->url('album', array('action' => 'add')));
 $albumForm->prepare();

 echo $this->form()->openTag($albumForm);
 echo $this->formHidden($albumForm->get('id'));
 
 echo $this->formRow($albumForm->get('title'));
 
 echo $this->formRow($albumForm->get('artist'));
 
 echo '<br />'.$this->formSubmit($albumForm->get('submit'));
 echo $this->form()->closeTag();